package com.mobius.software.android.iotbroker.main.dal;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.mobius.software.android.iotbroker.main.dal.Messages;
import com.mobius.software.android.iotbroker.main.dal.Topics;
import com.mobius.software.android.iotbroker.main.dal.Accounts;

import com.mobius.software.android.iotbroker.main.dal.MessagesDao;
import com.mobius.software.android.iotbroker.main.dal.TopicsDao;
import com.mobius.software.android.iotbroker.main.dal.AccountsDao;

/**
 * Mobius Software LTD
 * Copyright 2015-2017, Mobius Software LTD
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messagesDaoConfig;
    private final DaoConfig topicsDaoConfig;
    private final DaoConfig accountsDaoConfig;

    private final MessagesDao messagesDao;
    private final TopicsDao topicsDao;
    private final AccountsDao accountsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        topicsDaoConfig = daoConfigMap.get(TopicsDao.class).clone();
        topicsDaoConfig.initIdentityScope(type);

        accountsDaoConfig = daoConfigMap.get(AccountsDao.class).clone();
        accountsDaoConfig.initIdentityScope(type);

        messagesDao = new MessagesDao(messagesDaoConfig, this);
        topicsDao = new TopicsDao(topicsDaoConfig, this);
        accountsDao = new AccountsDao(accountsDaoConfig, this);

        registerDao(Messages.class, messagesDao);
        registerDao(Topics.class, topicsDao);
        registerDao(Accounts.class, accountsDao);
    }
    
    public void clear() {
        messagesDaoConfig.getIdentityScope().clear();
        topicsDaoConfig.getIdentityScope().clear();
        accountsDaoConfig.getIdentityScope().clear();
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public TopicsDao getTopicsDao() {
        return topicsDao;
    }

    public AccountsDao getAccountsDao() {
        return accountsDao;
    }

}
