package com.mobius.software.android.iotbroker.mqtt.dal;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mobius.software.android.iotbroker.mqtt.dal.Accounts;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCOUNTS".
*/
public class AccountsDao extends AbstractDao<Accounts, Long> {

    public static final String TABLENAME = "ACCOUNTS";

    /**
     * Properties of entity Accounts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        public final static Property ClientID = new Property(3, String.class, "clientID", false, "CLIENT_ID");
        public final static Property ServerHost = new Property(4, String.class, "serverHost", false, "SERVER_HOST");
        public final static Property CleanSession = new Property(5, Integer.class, "cleanSession", false, "CLEAN_SESSION");
        public final static Property KeepAlive = new Property(6, Integer.class, "keepAlive", false, "KEEP_ALIVE");
        public final static Property Will = new Property(7, String.class, "will", false, "WILL");
        public final static Property WillTopic = new Property(8, String.class, "willTopic", false, "WILL_TOPIC");
        public final static Property Qos = new Property(9, Integer.class, "qos", false, "QOS");
        public final static Property IsDefault = new Property(10, Integer.class, "isDefault", false, "IS_DEFAULT");
        public final static Property IsRetain = new Property(11, Integer.class, "isRetain", false, "IS_RETAIN");
        public final static Property Port = new Property(12, Integer.class, "port", false, "PORT");
    };

    private DaoSession daoSession;


    public AccountsDao(DaoConfig config) {
        super(config);
    }
    
    public AccountsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCOUNTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"PASSWORD\" TEXT," + // 2: password
                "\"CLIENT_ID\" TEXT," + // 3: clientID
                "\"SERVER_HOST\" TEXT," + // 4: serverHost
                "\"CLEAN_SESSION\" INTEGER," + // 5: cleanSession
                "\"KEEP_ALIVE\" INTEGER," + // 6: keepAlive
                "\"WILL\" TEXT," + // 7: will
                "\"WILL_TOPIC\" TEXT," + // 8: willTopic
                "\"QOS\" INTEGER," + // 9: qos
                "\"IS_DEFAULT\" INTEGER," + // 10: isDefault
                "\"IS_RETAIN\" INTEGER," + // 11: isRetain
                "\"PORT\" INTEGER);"); // 12: port
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCOUNTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Accounts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(3, password);
        }
 
        String clientID = entity.getClientID();
        if (clientID != null) {
            stmt.bindString(4, clientID);
        }
 
        String serverHost = entity.getServerHost();
        if (serverHost != null) {
            stmt.bindString(5, serverHost);
        }
 
        Integer cleanSession = entity.getCleanSession();
        if (cleanSession != null) {
            stmt.bindLong(6, cleanSession);
        }
 
        Integer keepAlive = entity.getKeepAlive();
        if (keepAlive != null) {
            stmt.bindLong(7, keepAlive);
        }
 
        String will = entity.getWill();
        if (will != null) {
            stmt.bindString(8, will);
        }
 
        String willTopic = entity.getWillTopic();
        if (willTopic != null) {
            stmt.bindString(9, willTopic);
        }
 
        Integer qos = entity.getQos();
        if (qos != null) {
            stmt.bindLong(10, qos);
        }
 
        Integer isDefault = entity.getIsDefault();
        if (isDefault != null) {
            stmt.bindLong(11, isDefault);
        }
 
        Integer isRetain = entity.getIsRetain();
        if (isRetain != null) {
            stmt.bindLong(12, isRetain);
        }
 
        Integer port = entity.getPort();
        if (port != null) {
            stmt.bindLong(13, port);
        }
    }

    @Override
    protected void attachEntity(Accounts entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Accounts readEntity(Cursor cursor, int offset) {
        Accounts entity = new Accounts( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // password
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // clientID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // serverHost
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // cleanSession
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // keepAlive
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // will
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // willTopic
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // qos
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // isDefault
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // isRetain
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12) // port
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Accounts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClientID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setServerHost(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCleanSession(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setKeepAlive(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setWill(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWillTopic(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setQos(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIsDefault(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setIsRetain(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setPort(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Accounts entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Accounts entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
