package com.mobius.software.android.iotbroker.mqtt.dal;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.mobius.software.android.iotbroker.mqtt.dal.Messages;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGES".
*/
public class MessagesDao extends AbstractDao<Messages, Long> {

    public static final String TABLENAME = "MESSAGES";

    /**
     * Properties of entity Messages.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MessageItem = new Property(1, String.class, "messageItem", false, "MESSAGE_ITEM");
        public final static Property Qos = new Property(2, Integer.class, "qos", false, "QOS");
        public final static Property IsIncoming = new Property(3, Integer.class, "isIncoming", false, "IS_INCOMING");
        public final static Property TopicName = new Property(4, String.class, "topicName", false, "TOPIC_NAME");
        public final static Property AccountID = new Property(5, long.class, "accountID", false, "ACCOUNT_ID");
    };

    private Query<Messages> accounts_MessageAccountQuery;

    public MessagesDao(DaoConfig config) {
        super(config);
    }
    
    public MessagesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESSAGE_ITEM\" TEXT," + // 1: messageItem
                "\"QOS\" INTEGER," + // 2: qos
                "\"IS_INCOMING\" INTEGER," + // 3: isIncoming
                "\"TOPIC_NAME\" TEXT," + // 4: topicName
                "\"ACCOUNT_ID\" INTEGER NOT NULL );"); // 5: accountID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Messages entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String messageItem = entity.getMessageItem();
        if (messageItem != null) {
            stmt.bindString(2, messageItem);
        }
 
        Integer qos = entity.getQos();
        if (qos != null) {
            stmt.bindLong(3, qos);
        }
 
        Integer isIncoming = entity.getIsIncoming();
        if (isIncoming != null) {
            stmt.bindLong(4, isIncoming);
        }
 
        String topicName = entity.getTopicName();
        if (topicName != null) {
            stmt.bindString(5, topicName);
        }
        stmt.bindLong(6, entity.getAccountID());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Messages readEntity(Cursor cursor, int offset) {
        Messages entity = new Messages( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // messageItem
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // qos
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // isIncoming
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // topicName
            cursor.getLong(offset + 5) // accountID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Messages entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMessageItem(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setQos(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setIsIncoming(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTopicName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAccountID(cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Messages entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Messages entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "messageAccount" to-many relationship of Accounts. */
    public List<Messages> _queryAccounts_MessageAccount(long accountID) {
        synchronized (this) {
            if (accounts_MessageAccountQuery == null) {
                QueryBuilder<Messages> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccountID.eq(null));
                accounts_MessageAccountQuery = queryBuilder.build();
            }
        }
        Query<Messages> query = accounts_MessageAccountQuery.forCurrentThread();
        query.setParameter(0, accountID);
        return query.list();
    }

}
