package com.mobius.software.android.iotbroker.mqtt.dal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TOPICS".
 */
public class Topics {

    private Long id;
    private Integer qos;
    private String topicName;
    private long accountID;

    public Topics() {
    }

    public Topics(Long id) {
        this.id = id;
    }

    public Topics(Long id, Integer qos, String topicName, long accountID) {
        this.id = id;
        this.qos = qos;
        this.topicName = topicName;
        this.accountID = accountID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getQos() {
        return qos;
    }

    public void setQos(Integer qos) {
        this.qos = qos;
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public long getAccountID() {
        return accountID;
    }

    public void setAccountID(long accountID) {
        this.accountID = accountID;
    }

}
